### PR TITLE
a better handling of while keyword

### LINKED ISSUE #314: Check while loop
I have been fooled several time by a while conditio that looks like:
````yaml
- while(condition):
  - do_something()
````
It is not executed and do not produce error.
At least in version 0.12.0
It is wotrh testing on master branch and prevent it to happen agian if needed.

### PR DESCRIPTION
**Pull request by benjello**
Fix #314 
Both statements should work:
```yaml
- while some_condition:
  - do_something()

- while(some_condition):
  - do_something()
```

### CODE REVIEW

**Comment by benjello** [comment]
@gdementen : I let you check the changelog, change it if needed and merge.

**Comment by benjello** [comment]
@gdementen : should I merge it ?

**Comment by gdementen** [comment]
I don't expect you to, but you may do it if you need it before I get to it (somewhere in december). I will make the changelog message to my taste (😉) and merge it.

**Comment by benjello** [comment]
OK thanks. I will merge it because it simplifies our process at ipp.

**Pull request merged**
