### PR TITLE
WIP: fix alignement to handle python bool filters

### PR DESCRIPTION
**Pull request by benjello**

### CODE REVIEW

**Comment by benjello** [comment]
Added an example that breaks the original version.
But my fix produces another error and I didn't manage to solve it locally.

**Comment by benjello** [comment]
The `IndexError` was already there !

**Comment by benjello** [comment]
@gdementen your help is needed here ;-)

**Comment by benjello** [comment]
Rebasing done.

**Comment by gdementen** [comment]
this is looking mostly good. Could you add a note in the changelog and squash your commits?

**Comment by benjello** [comment]
Done

**Comment by gdementen** [comment]
I don't see any change in the changelog ???

**Comment by benjello** [comment]
Sorry missed this one.

**Comment by benjello** [comment]
Done

**Comment by gdementen** [comment]
LGTM, Thanks!

**Pull request merged**
