### PR TITLE
Fix cpartition import

### PR DESCRIPTION
**Pull request by benjello**
Let us check if this solves the travis tests

### CODE REVIEW

**Comment by benjello** [comment]
BTW @gdementen : could you add me as a collaborator on this project so I can store branches here instead on my fork ? And of course you can and should protect the master branch !

**Comment by gdementen** [comment]
I have added you as collaborator on the project, but I have given you full access to the repo as it was easier to configure. Just be careful where you push 😉

**Comment by gdementen** [comment]
btw, I am aware of the larray failure. Just haven't had time to dig into that...

**Comment by benjello** [comment]
@gdementen : can I protect the master branch ?

**Comment by benjello** [comment]
Well I do not have access to setting so I can't.

**Comment by gdementen** [comment]
what kind of protection do you have in mind?

**Comment by benjello** [comment]
You can protect the master branch from a direct push so it can evolve only through merges or a push by the maintainer

**Comment by gdementen** [comment]
@benjello I have added protection to master...

**Pull request merged**
