### PR TITLE
WIP: Avoid looking for globals in entity fields during matching

### PR DESCRIPTION
**Pull request by benjello**
A small fix to be able to use matching whit ha score given by a table (see #294 ).

cc @benbel

### CODE REVIEW

**Comment by gdementen** [comment]
@benjello: Thanks a lot for this. It was a simple fix like a thought... But the problem wasn't exactly where I thought it was. Nice catch. 

So, this PR looks go to me in principle, but would it be too much to ask for a changelog entry and a testcase?

**Comment by benjello** [comment]
@gdementen : yes @benbel and I will provide a test_case.
This patch fix some problems but we still have some trouble with the call to tables and we used the following `array` trick to bypass an error:
```yaml
- id_of_match: matching(
            set1filter = (sexe == 0),
            set2filter = (sexe == 1),
            orderby = "EDtM",
            score = array(score_table)[x, other.x],
            algo = "byvalue"
            )
```

**Comment by benbel** [comment]
@gdementen : would the minimal example of issue #294 be a good test case?

**Comment by gdementen** [comment]
@benbel : that is a great base indeed (I love minimal examples like this!). Just remove the function and expression parts and add a few checks on the result (to check that the result is as expected) and not only that the matching function does not crash.

**Comment by gdementen** [comment]
> @gdementen : yes @benbel and I will provide a test_case.

Thanks.

> This patch fix some problems but we still have some trouble with the call to tables and we used the following `array` trick to bypass an error:
> 
> ```yaml
> - id_of_match: matching(
>             set1filter = (sexe == 0),
>             set2filter = (sexe == 1),
>             orderby = "EDtM",
>             score = array(score_table)[x, other.x],
>             algo = "byvalue"
>             )
> ```
This is a nasty workaround. It would be nice if this could be resolved too, because here you are lucky your x (and other.x) labels correspond to their indices (label 0 is at position 0, label 1 is at position 1), otherwise you'd get awful results.

**Comment by benbel** [comment]
> @benbel : that is a great base indeed (I love minimal examples like this!). Just remove the function and expression parts and add a few checks on the result (to check that the result is as expected) and not only that the matching function does not crash.

[mwe.zip](https://github.com/liam2/liam2/files/2763861/mwe.zip)

**Comment by gdementen** [comment]
@benjello: could you incorporate that in the PR? or even better, incorporate that test into the existing matching.yml?

As a side note, minimal tests are even more minimal when the test data is created/generated within the model like in the test_issueXXX models so that we don't need the import step.

**Comment by benjello** [comment]
@gdementen : I converted @benbel 's test in the format of liam2 issues.
Could you look at the bug that appears when we remove the `array` for the keyword `score` in the matching function and give us with some guidance to solve it ?

Thanks !

**Comment by benbel** [comment]
@gdementen : is there anything else we should do?

**Comment by gdementen** [comment]
@benbel I will try to look at this as soon as I can. I hope to finally release 0.13 sometime this summer and this will be in it.

**Comment by benjello** [comment]
@gdementen : any chance to see this pR merged anytime soon ... ?

**Comment by gdementen** [comment]
I can merge this as-is "now" if that helps but you have to know two things: 1) the implementation **will** change before the release (which I have no idea when it will happen). 2) but I have no idea when (if?) I will ever have time to make that release. I still need a few weeks free from other projects to do it, but those weeks are not anywhere in sight :-/

Note that I have fixed the issue properly in the devel branch (see https://github.com/liam2/liam2/commit/94538c380b1341998aeec1f0c9855543edcf7205) but I don't remember whether the devel branch is in a usable state or not.

**Comment by benjello** [comment]
@gdementen: a merge as-is is ok form me !

**Pull request merged**
